package com.brightcove.consulting.api.query;

public enum VideoField {

    ID, NAME, SHORT_DESCRIPTION, LONG_DESCRIPTION, CREATION_DATE, PUBLISHED_DATE,
    LAST_MODIFIED_DATE, START_DATE, END_DATE, LINK_URL, LINK_TEXT,
    TAGS, VIDEO_STILL_URL, THUMBNAIL_URL, REFERENCE_ID, LENGTH, ECONOMICS,
    ITEM_STATE, PLAYS_TOTAL, PLAYS_TRAILING_WEEK, VERSION, CUE_POINTS, SUBMISSION_INFO,
    CUSTOM_FIELDS, RELEASE_DATE, FLV_URL, IOS_RENDITIONS, RENDITIONS, GEO_FILTERED,
    GEO_FILTER_EXCLUDE, EXCLUDE_LIST_COUNTRIES, GEO_FILTERED_COUNTRIES, ALLOWED_COUNTRIES,
    ACCOUNT_ID, FLV_FULL_LENGTH, VIDEO_FULL_LENGTH

}
